// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY6Phb-0ovkyIqL_Ky0b7h2liIZPychWY',
    appId: '1:476585004117:web:b9c622bb546657531618dc',
    messagingSenderId: '476585004117',
    projectId: 'gestionnotes-eb178',
    authDomain: 'gestionnotes-eb178.firebaseapp.com',
    storageBucket: 'gestionnotes-eb178.firebasestorage.app',
    measurementId: 'G-DQDEYLQJK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALedYIchfJ0_1XzNP-4RFwTR3jufOjmVM',
    appId: '1:476585004117:android:de0445f0c7ef6ae81618dc',
    messagingSenderId: '476585004117',
    projectId: 'gestionnotes-eb178',
    storageBucket: 'gestionnotes-eb178.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnCsWSF08RgHme3G4W1jv2WGEpL7TXJWQ',
    appId: '1:476585004117:ios:b6e4298c3bdda1401618dc',
    messagingSenderId: '476585004117',
    projectId: 'gestionnotes-eb178',
    storageBucket: 'gestionnotes-eb178.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnCsWSF08RgHme3G4W1jv2WGEpL7TXJWQ',
    appId: '1:476585004117:ios:b6e4298c3bdda1401618dc',
    messagingSenderId: '476585004117',
    projectId: 'gestionnotes-eb178',
    storageBucket: 'gestionnotes-eb178.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY6Phb-0ovkyIqL_Ky0b7h2liIZPychWY',
    appId: '1:476585004117:web:c01f28aa1d3bb5f71618dc',
    messagingSenderId: '476585004117',
    projectId: 'gestionnotes-eb178',
    authDomain: 'gestionnotes-eb178.firebaseapp.com',
    storageBucket: 'gestionnotes-eb178.firebasestorage.app',
    measurementId: 'G-YW1QE06R18',
  );
}
